### ISSUE TITLE
这个改变的有益效果是什么？

### ISSUE THREAD

**Issue by MaxMax2016** [azraelkuan/repgan#1]

**Comment by azraelkuan** [comment]
the speed is much faster than hifigan with a little quality decay.

**Comment by WhiteFu** [comment]
How much can the model speed up ？

**Comment by azraelkuan** [comment]
with my config, the RTF of hifigan v1 is 0.290, and repgan is 0.144

**Comment by WhiteFu** [comment]
Thanks for your reply, great job, i will try it.
