### ISSUE TITLE
why still (3 7 11)

### ISSUE THREAD

**Issue by hdmjdp** [azraelkuan/repgan#2]
https://github.com/azraelkuan/repgan/blob/f6fd81e342ac96ecd1eba4d6a9984c601eb13cc2/repgan.py#L79

 As you say, "For example: HiFiGAN use 3, 7, 11 as the kernel sizes in the ResnetBlock, and using RepGAN, we only have one kernel size 11"

**Comment by azraelkuan** [comment]
in training, we also have three resnetblock **3, 7, 11**, but in inference, we will fuse three kernel size into one, **11**, u can check the **inference** function in `rep_conv`

**Comment by hdmjdp** [comment]
> in training, we also have three resnetblock **3, 7, 11**, but in inference, we will fuse three kernel size into one, **11**, u can check the **inference** function in `rep_conv`

ok, thanks, I will check it.

**Comment by hdmjdp** [comment]
@azraelkuan do it this way, whether training and inference exist gap?

**Comment by azraelkuan** [comment]
no quality gap, the weight is equal in training and inference

**Comment by hdmjdp** [comment]
@azraelkuan thanks, another question, you generator does not have skip connetction(residual connect).  This is different from hifigan, without it, does quailty decay?


```
def forward(self, x):
        x = self.input_conv(x)

        for i in range(len(self.upsamples)):
            x = self.upsamples[i](x)
            if self.training:
                x = self.blocks[i](x)
            else:
                x = self.blocks[i].inference(x)
            x = self.non_linear(x)
        x = self.output_conv(x)
        return 

```

and in repconv

```
def forward(self, x: torch.Tensor) -> torch.Tensor:
        for idx in range(len(self.convs1)):
            x = self.act(x)
            x = self.convs1[idx](x)
            if self.use_additional_convs:
                x = self.act(x)
                x = self.convs2[idx](x)
        return x
```

and  resblock_dilations is different, origin len is 3, but yours is 4

**Comment by azraelkuan** [comment]
check this:
https://github.com/azraelkuan/repgan/blob/26323d2ff3dfe80bc660830eb33bcde237343330/rep_conv.py#L27

![image](https://user-images.githubusercontent.com/23380152/183828467-2035aa65-e1c0-4c08-8a11-434f1bf86b9f.png)

**Comment by hdmjdp** [comment]
Thank you very much!
