### ISSUE TITLE
Any quality degradation or improvement ?

### ISSUE THREAD

**Issue by rishikksh20** [azraelkuan/repgan#4]
As you mentioned it speed up to 2x in inference, any training speed up? And what about the quality of generated speech any noticeable improvement and degradation ?

**Comment by rishikksh20** [comment]
Any convergence improvement ?

**Comment by azraelkuan** [comment]
Sorry, i can not show u some samples for the internal dataset.
It does not speed up training time, the same with hifigan, but inference is much faster.
for convergence, i suggest to use the D in univnet, it works much better than hifigan MPD.
check this: https://github.com/mindslab-ai/univnet

**Comment by rishikksh20** [comment]
@azraelkuan One more question 
Is it necessary to do this
 ```python
 voc.convert_weight_bias()
 voc.eval()
 ```
 on each validation step ?

**Comment by azraelkuan** [comment]
yes, u need to call `convert_weight_bias` and `eval()` before validation, 
also u can create a new inference function.
