### ISSUE TITLE
和原始hifigan结构并非等价的。

### ISSUE THREAD

**Issue by splinter21** [azraelkuan/repgan#6]
原始hifigan是3-7-11的kernel在外面大并行，而你的实现版本是3-7-11的kernel在最里面小并行。

**Comment by splinter21** [comment]
原版：l3l3rl3l3rl3l3r+l7l7rl7l7rl7l7r+l11l11rl11l11rl11l11r
你的版本：l33771111rl33771111rl33771111r
l指lrelu，r指res，33771111指（conv3|dil1->dil_x+conv7|dil1->dil_x+conv11|dil1->dil_x）

**Comment by splinter21** [comment]
不知道如何评价效果的增减。诸位有做过实验发现效果有差异的吗？

**Comment by azraelkuan** [comment]
如果想并行，肯定是不能等价的，会有一点效果差异
